apiVersion: apps/v1
kind: Deployment
metadata:
  name: javademo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javademo2
  template:
    metadata:
      labels:
        app: javademo2
    spec:
      containers:
      - name: javademo2
        image: ckacr001.azurecr.cn/javademo:63
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: javademo2
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
spec:
  type:
    LoadBalancer
  selector:
    app: javademo2
  ports:
  - port: 80
    targetPort: 8080

